# Generated by Django 6.0.2 on 2026-04-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
