# Generated by Django 6.0.4 on 2026-04-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='balance',
        ),
    ]
