# Generated by Django 6.0.4 on 2026-04-26 18:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_remove_payout_idempotency_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='bank_account_id',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='payout',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
