# Generated by Django 6.0.4 on 2026-04-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_remove_payout_bank_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='idempotency_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
