# Generated by Django 6.0.4 on 2026-04-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idempotency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='key',
            field=models.UUIDField(),
        ),
    ]
