# Generated by Django 6.0.4 on 2026-04-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idempotency', '0002_alter_idempotencykey_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idempotencykey',
            old_name='response',
            new_name='response_data',
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
